version: '3.9'

services:

  adminer: 
    image: adminer 
    ports:
        - 8081:8080
    depends_on:
        - db
  
  app: 
    build: . 
    volumes:
        - .:/app/
    ports:
        - 8080:8000
    depends_on:
        - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    env_file:
        - .env
    ports:
        - 5432:5432
