# Generated by Django 5.0.6 on 2024-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='task',
            name='weather',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Weather'),
        ),
    ]
