# Generated by Django 5.0.6 on 2024-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_options_alter_task_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='backgroundcolor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'To do'), (2, 'Done')], default=1, verbose_name='Status'),
        ),
    ]
